/**
 * roll-prefab — outer roller: drive real headless sessions until one is
 * perfect, then export its durable log as the prefab template.
 *
 * Usage:
 *   node prefab/roll-prefab.mjs --cwd "E:/Desktop/mytests/modeltest/workspace" \
 *       [--attempts 6] [--out prefab/template.jsonl]
 *
 * Requires DSH_HARNESS_ROOT (a harness checkout with apps/cli/lib/bin.js).
 * Each attempt boots the headless profile with the roll-runner plugin, sends
 * the anchor task then the loading task, and parses the PREFAB_RESULT line.
 * On success the session's session.jsonl.zstd is located by scanning the
 * store for the reported session id, decompressed (zstd multi-frame), and
 * saved as the plaintext template.
 */

import { spawnSync } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, copyFileSync, rmSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { homedir } from 'node:os'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const HARNESS = process.env.DSH_HARNESS_ROOT
const LAUNCHER = HARNESS && join(HARNESS, 'apps', 'cli', 'lib', 'bin.js')
const DSH_HOME = process.env.DSH_HOME ?? join(homedir(), '.dsh')
const PROFILE_DIR = join(DSH_HOME, 'profiles', 'headless')

const ANCHOR_TASK = 'Read the workspace-root AGENTS.md completely before any future maintenance work. Use bash with exactly this command: cat ./AGENTS.md. Do not inspect or list anything else, and do not quote, summarize, or discuss the file contents. When the complete file has been read, reply only: Instructions loaded.'
const LOAD_TASK = 'Set up the tool surface for the maintenance work in four sequential steps, using exactly one tool call in each assistant response and waiting for its result before continuing. Step 1: dev_tool_search unlock read, write, edit, glob, and grep. Step 2: dev_tool_search unlock ask_user_question, todo_write, and web_search. Step 3: skill_search with query code. Step 4: skill_search with query document. Do not combine steps or make parallel calls. After step 4, make no more tool calls and reply only: Ready. Do not inspect or mention any workspace project, directory, README, or source file, and do not summarize any tool or skill result.'

const args = process.argv.slice(2)
const opt = (name, fallback) => {
  const hit = args.find((a) => a.startsWith(`--${name}=`))
  if (hit) return hit.slice(name.length + 3)
  const index = args.indexOf(`--${name}`)
  return index >= 0 && args[index + 1] !== undefined && !args[index + 1].startsWith('--')
    ? args[index + 1]
    : fallback
}
const cwd = opt('cwd')
const attempts = Number(opt('attempts', '6'))
const out = opt('out', join(HERE, 'template.jsonl'))
const anchorTask = opt('anchor-task', ANCHOR_TASK)
const loadTask = opt('load-task', LOAD_TASK)
if (cwd === undefined || !existsSync(LAUNCHER)) {
  console.error('usage: node prefab/roll-prefab.mjs --cwd <dir> [--attempts N] [--out file]  (DSH_HARNESS_ROOT required)')
  process.exit(2)
}

function findSessionFile(sessionId) {
  const root = join(DSH_HOME, 'sessions')
  if (!existsSync(root)) return undefined
  for (const group of readdirSync(root, { withFileTypes: true })) {
    if (!group.isDirectory()) continue
    for (const entry of readdirSync(join(root, group.name), { withFileTypes: true })) {
      if (!entry.isDirectory() || entry.name !== sessionId) continue
      const file = join(root, group.name, entry.name, 'session.jsonl.zstd')
      return existsSync(file) ? file : undefined
    }
  }
  return undefined
}

/** Decode a multi-frame zstd session log via Python (Node's one-shot API stops at frame 1). */
function decodeZstd(file) {
  const result = spawnSync('python', ['-c', 'import sys; from compression import zstd; sys.stdout.buffer.write(zstd.decompress(open(sys.argv[1],"rb").read()))', file], {
    encoding: 'buffer', maxBuffer: 512 * 1024 * 1024,
  })
  if (result.status !== 0) throw new Error(`zstd decode failed: ${result.stderr?.toString().slice(0, 300)}`)
  return result.stdout.toString('utf8')
}

mkdirSync(PROFILE_DIR, { recursive: true })
const runToken = randomUUID()
const runnerName = `prefab-roll-runner-${runToken}.mjs`
const runnerFile = join(PROFILE_DIR, runnerName)
const patchFile = join(PROFILE_DIR, `prefab-roll-${runToken}.yml`)
copyFileSync(join(HERE, 'roll-runner.mjs'), runnerFile)

let template = null
try {
  for (let attempt = 1; attempt <= attempts && template === null; attempt += 1) {
    const patch = `# Generated by prefab/roll-prefab.mjs (attempt ${attempt})
- id: headless-startup
  disabled: true

- id: headless-runner
  disabled: true

- insert:
    - id: agent-presets
      name: '@deepseek-ai/dsh-agent-presets'
      config:
        default: standard

    - id: roll-runner
      name: ./${runnerName}
      config:
        anchorTask: ${JSON.stringify(anchorTask)}
        loadTask: ${JSON.stringify(loadTask)}
        preset: anchored-standard
        cwd: ${JSON.stringify(cwd)}
`
    writeFileSync(patchFile, patch)
    console.log(`— attempt ${attempt}/${attempts}`)
    const result = spawnSync(process.execPath, [LAUNCHER, '--profile', 'headless', '--patch', patchFile], {
      cwd: HARNESS, encoding: 'utf8', timeout: 600_000, env: process.env,
    })
    rmSync(patchFile, { force: true })
    const line = (result.stdout ?? '').split('\n').find((l) => l.startsWith('PREFAB_RESULT: '))
    if (line === undefined) {
      console.error(`  no verdict (exit ${result.status}); stderr: ${(result.stderr ?? '').slice(-400)}`)
      continue
    }
    const verdict = JSON.parse(line.slice('PREFAB_RESULT: '.length))
    console.log(`  styleOk=${verdict.styleOk} flowOk=${verdict.flowOk} rich=${verdict.effectiveReasoningCount ?? 0} letMeHits=${verdict.letMeHits} unlocked=[${(verdict.unlockedNames ?? []).join(',')}] agentsMd=${verdict.readAgentsMd} skills=${verdict.skillSearched}`)
    console.log(`  first: ${(verdict.firstLines ?? [])[0] ?? '(none)'}`)
    if (verdict.ok !== true) continue
    const file = findSessionFile(verdict.sessionId)
    if (file === undefined) {
      console.error(`  verdict ok but session file not found for ${verdict.sessionId}`)
      continue
    }
    const text = decodeZstd(file)
    template = { verdict, file, text }
  }
} finally {
  rmSync(patchFile, { force: true })
  rmSync(runnerFile, { force: true })
}

if (template === null) {
  console.error(`no perfect roll in ${attempts} attempts`)
  process.exit(1)
}
writeFileSync(out, template.text)
writeFileSync(`${out}.meta.json`, JSON.stringify({
  rolledAt: new Date().toISOString(),
  cwd,
  sessionId: template.verdict.sessionId,
  unlockedNames: template.verdict.unlockedNames,
  firstLines: template.verdict.firstLines,
}, null, 2))
console.log(`template saved: ${out} (${template.text.length} chars, source ${template.verdict.sessionId})`)
